/** Declaration file generated by dts-gen */

export const fileExtensions: {
    "image/jpeg": string;
    "image/jpg": string;
    "image/png": string;
    "text/html": string;
    "text/plain": string;
};

export const verbose: boolean;

export function build(data: any, options: any, callback: any): void;

export function getBoundary(contentType: any): any;

export function getCharset(contentType: any): any;

export function getEmailAddress(raw: any): any;

export function getFileExtension(mimeType: any): any;

export function parse(eml: any, options: any, callback: any): void;

export function read(eml: any, options: any, callback: any): any;

export function toEmailAddress(data: any): any;

export function unpack(eml: any, directory: any, options: any, callback: any): any;

export function unquotePrintable(s: any, charset: any): any;

export function unquoteString(s: any): any;

export function unquoteUTF8(s: any): any;

